---

# Resource to sync all repos in GitHub Organization or user account
#
# What it does:
#   - Get list of repos, skipping archived ones
#   - Generate RSA "deploy key" and add it to repository via API
#   - Clone repositories with HEAD refs
#   - Scan those for "app.yaml" files

apiVersion: mycorp.agrrh.com/v1alpha1
kind: GitHubOrg

metadata:
  name: mycorp
  namespace: mycorp

spec:
  # Place a name of your organization/user here
  organization: mycorp  # Not really exists

  # Repositories to include in sync
  #   Setting this list to non-empty value would limit sync to this repo names and regexps
  include: []
  # include:
  #   - repo-name
  #   - '^go-(.+)$'  # would be treated as regexp if starts with "^" and ends with "$"

  # Exclusion list
  #   Same as above, but excludes repos from being synced
  exlclude: []
  # exclude:
  #   - skip-this
  #   - '^infra-(.+)$'
  #   - '^sec-(.+)$'

  # GitHub API token with access to deploy keys
  githubTokenSecret: secret-name:key-name

  # For private repos with SSH access
  url: git@github.com:agrrh/mycorp.git
  sshKeySecret: secret-name:key-name
