---

# Resource to sync single repository

apiVersion: mycorp.agrrh.com/v1alpha1
kind: Repository

metadata:
  name: my-repo
  namespace: mycorp

spec:
  # For public repos, use HTTPS
  url: https://github.com/agrrh/mycorp.git

  # Private repos with access tokens
  # url: https://$user:$password@gitlab.com/example/foo.git
  # userSecret: secret-name:key-name
  # passwordSecret: secret-name:key-name

  # For private repos with SSH access
  # url: git@github.com:agrrh/mycorp.git
  # sshKeySecret: secret-name:key-name
