---

apiVersion: mycorp.agrrh.com/v1alpha1
kind: Team

metadata:
  # Evade abstract names like "backend"
  #   Team name must represent product or service you are work on
  #   Prefer business function in such case, e.g. "shop", "cart"
  name: antifraud-ai
  namespace: mycorp

spec: {}
